### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2021-b-qgis-google-sheets-plugin#10]
target file: https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/blob/master/google_sheets_downloader2/help/source/index.rst

Example: https://github.com/ctu-fgis/2021-c-qgis-ruain-plugin/blob/master/docs/source/popis.rst

**Comment by monikakrizova** [comment]
Documentation as a rst file created:

https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/tree/master/help/source/index.rst

Documentation as a html file was also created by using Sphinx, but the GitHub page wasn't generated.

https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/blob/master/help/build/html/index.html

**Comment by landam** [comment]
Documentation deployed: https://ctu-fgis.github.io/2021-b-qgis-google-sheets-plugin/
