### ISSUE TITLE
load data also when project is not created

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2021-b-qgis-google-sheets-plugin#11]

**Comment by monikakrizova** [comment]
solved in commit [cbc829d986d7edf20e3e23d2d2a2a576f35715ec](https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/commit/cbc829d986d7edf20e3e23d2d2a2a576f35715ec)

**Comment by Hoffmma5** [comment]
Changed current file path to the plugin folder, looking for token and creating token inside this folder.

**Comment by landam** [comment]
Confirmed
