### ISSUE TITLE
target layer: assign crs 

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2021-b-qgis-google-sheets-plugin#9]
```
&crs=epsg:4326
```

**Comment by Hoffmma5** [comment]
Solved by adding authid() function to the QgsCoordinateReferenceSystem class.

**https://github.com/ctu-fgis/2021-b-qgis-google-sheets-plugin/blob/master/google_sheets_downloader/google_sheets_downloader.py#:~:text=self.CRS%20%3D%20self.dockwidget.selectCRS.crs().authid()**
